apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-exercise
  labels:
    app: flask-app-exercise
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask-app-exercise
  template:
    metadata:
      labels:
        app: flask-app-exercise
    spec:
      containers:
        - name: flask-container-exercise
          image: amckee457/flask-app-kubernetes:latest
          ports:
            - containerPort: 5000        
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-exercise
spec:
  type: ClusterIP
  selector:
    app: flask-app-exercise
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000