apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: amckee457/db-kubernetes
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-exercise
spec:
  type: ClusterIP
  selector:
    app: mysql-exercise
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306